### ISSUE TITLE
Key layout to print and try out?

### ISSUE THREAD

**Issue by mejobloggs** [mylestunglee/articulation70#1]
Hello, is there a key layout image available for printing? Or a way to generate it via freecad etc?

I want to see how it feels with my hands.

I also wanted to leave a comment saying how awesome this keyboard looks. You've done amazing work and I'm very impressed by the details of instructions and adjustable layout in freecad and all the thought you've put into this. Very cool

**Comment by mylestunglee** [comment]
Hello @mejobloggs ,

Thank you for the kind words. There are a couple of ways to do this, however I think by exporting the layers in FreeCad as an SVG, then printing this should be a good approximation. I've attached a PDF with the default layout. The FreeCad layout does not show the pinky stagger variation but it is fixed to ±1mm but it is up to you if you want to use it. I suppose there should be a way via KiCad, but I would guess it would be more tedious. Hope this helps.

[layout.pdf](https://github.com/mylestunglee/articulation70/files/13851789/layout.pdf)

**Comment by mejobloggs** [comment]
Thanks very much 👍
